image: jelaniwoods/appdev2021-omnicalc-1@sha256:06f8167ddbae7d1c511a37264efeb34dbcef12245ce736f3adc69dc5092cf2fc

tasks:
  - command: bundle install
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - Vense.rails-snippets
    - wingrunr21.vscode-ruby
